### Get All Position

GET {{BASE_URL}}/api/position/all?limit=10&offset=0 HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Create Position

POST {{BASE_URL}}/api/position/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test 1",
  "color": "#fffff",
  "name": "Testing 1",
  "short_name": "Test 1 Short name"
}


### Update Position

PUT {{BASE_URL}}/api/position/update HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test",
  "color": "#f1983",
  "id": 30,
  "name": "Testing",
  "short_name": "Test Short name"
}


### Delete Position

DELETE {{BASE_URL}}/api/position/delete?id=31 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get All Level

GET {{BASE_URL}}/api/level/all?limit=20&offset=0 HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Create Level

POST {{BASE_URL}}/api/level/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test 1",
  "color": "#fffff",
  "display_name": "Test 1 Short name",
  "name": "Testing 1"
}


### Update Level

PUT {{BASE_URL}}/api/level/update HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test 2",
  "color": "#f1983",
  "display_name": "Test Display name changed",
  "id": 35,
  "name": "Testing Changed"
}


### Delete Level

DELETE {{BASE_URL}}/api/level/delete?id=34 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get All User Type

GET {{BASE_URL}}/api/user-type/all?limit=20&offset=0 HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Create User Type

POST {{BASE_URL}}/api/user-type/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test 1",
  "name": "Testing 1"
}


### Update User Type

PUT {{BASE_URL}}/api/user-type/update HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "code": "test 2",
  "id": 12,
  "name": "Testing Changed"
}


### Delete User Type

DELETE {{BASE_URL}}/api/user-type/delete?id=12 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get working time

GET {{BASE_URL}}/api/working-time/abdeed38-642f-4435-829b-6a27a8d7f33c HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}
