### GET Permission

GET {{BASE_URL}}/api/permission/all HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### GET List Role

GET {{BASE_URL}}/api/role/all?limit=10&offset=4 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get Role with Permission by Id

GET {{BASE_URL}}/api/role?id=1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Create Role

POST {{BASE_URL}}/api/role/create HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}

{
  "description": "",
  "display_name": "something",
  "name": "something"
}


### Delete Role

DELETE {{BASE_URL}}/api/role/delete?id=15 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}
