### Create User

POST {{BASE_URL}}/api/user/create HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}
Content-Type: application/json

{
  "address": "Ho Chi Minh, Quan 2",
  "afternoon_end_at": "17:00",
  "afternoon_start_at": "13:00",
  "afternoon_working_time": 4,
  "avatar_path": "/avatars/user123.png",
  "bank_account": "918247129012",
  "branch_id": 1,
  "current_address": "123 Le Loi, Hanoi",
  "dob": "1995-07-15T00:00:00Z",
  "email": "test@gmail.com",
  "emergency_contact": "Tran Van B",
  "emergency_contact_phone": "09876543210",
  "gender": "male",
  "identify_issue_date": "2015-03-20T00:00:00Z",
  "identify_number": "012348127311",
  "identify_place": "Hanoi",
  "last_name": "Tuan",
  "level_id": 1,
  "mezon_id": "MEZON001",
  "morning_end_at": "12:00",
  "morning_start_at": "8:00",
  "morning_working_time": 4,
  "password": "password",
  "phone": "09123456781",
  "position_id": 3,
  "role_id": 9,
  "sur_name": "Nguyen",
  "tax_code": "TX1234",
  "user_type_id": 1
}


### Get All User

GET {{BASE_URL}}/api/user/all?limit=10&offset=0 HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get User By Email

GET {{BASE_URL}}/api/user/by-email?email=anh.truongdieu@ncc.asia HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Get User By Id

GET {{BASE_URL}}/api/user/abdeed38-642f-4435-829b-6a27a8d7f33c HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Delete User

DELETE {{BASE_URL}}/api/user?id=77f80e13-4bba-4b62-8354-10d12d893cdb HTTP/1.1
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}


### Login

POST {{BASE_URL}}/api/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "email": "tuan.phan@gmail.com",
  "password": "20102002"
}


### User Config

GET {{BASE_URL}}/api/user-config HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{JWT_TOKEN}}
